-- Follow-up manual completo do CRM-19-MOTORS.
-- O envio fica no n8n; o banco preserva os estados e movimenta respostas humanas.

alter table public."BASE_DE_LEADS"
  add column if not exists follow_manual text not null default 'inativo',
  add column if not exists ja_recebeu_msg text,
  add column if not exists erro_follow_manual text,
  add column if not exists etiquetas bigint[] not null default '{}'::bigint[];

create table if not exists public.pipeline_etapas (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  cor text not null,
  ordem integer not null,
  is_inicial boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pipeline_etapas_slug_check check (slug ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$' and length(slug) <= 60),
  constraint pipeline_etapas_nome_check check (length(btrim(nome)) between 1 and 60),
  constraint pipeline_etapas_cor_check check (cor ~ '^#[0-9A-Fa-f]{6}$'),
  constraint pipeline_etapas_ordem_check check (ordem >= 0),
  constraint pipeline_etapas_ordem_key unique (ordem) deferrable initially immediate
);

insert into public.pipeline_etapas (slug, nome, cor, ordem, is_inicial) values
  ('oportunidade', 'Oportunidade', '#22c55e', 0, true),
  ('em_qualificacao', 'Em Qualificação', '#38bdf8', 1, false),
  ('em_negociacao', 'Em Negociação', '#f97316', 2, false),
  ('follow_up', 'Follow-up', '#a855f7', 3, false),
  ('respondeu_follow_up', 'Respondeu Follow Up', '#990bda', 4, false),
  ('fechado', 'Fechado', '#16a34a', 5, false),
  ('nao_fechou', 'Não Fechou', '#ef4444', 6, false),
  ('pesquisa_atendimento', 'Lembrete Interno', '#06b6d4', 7, false),
  ('resgate', 'Resgate', '#f6dd3c', 8, false)
on conflict (slug) do nothing;

create or replace function public.pipeline_etapas_set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_pipeline_etapas_updated_at on public.pipeline_etapas;
create trigger trg_pipeline_etapas_updated_at
before update on public.pipeline_etapas
for each row execute function public.pipeline_etapas_set_updated_at();

create or replace function public.pipeline_etapa_protegida(p_slug text)
returns boolean language sql immutable as $$
  select p_slug in (
    'oportunidade', 'em_qualificacao', 'em_negociacao',
    'follow_up', 'respondeu_follow_up', 'resgate'
  );
$$;

create or replace function public.bloquear_alteracao_etapa_protegida()
returns trigger language plpgsql set search_path = public as $$
begin
  if public.pipeline_etapa_protegida(old.slug) and row(
    new.slug, new.nome, new.cor, new.ordem, new.is_inicial
  ) is distinct from row(
    old.slug, old.nome, old.cor, old.ordem, old.is_inicial
  ) then
    raise exception 'Esta etapa é protegida por automações e não pode ser alterada.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_bloquear_alteracao_etapa_protegida on public.pipeline_etapas;
create trigger trg_bloquear_alteracao_etapa_protegida
before update on public.pipeline_etapas
for each row execute function public.bloquear_alteracao_etapa_protegida();

create or replace function public.impedir_exclusao_etapa_protegida()
returns trigger language plpgsql set search_path = public as $$
begin
  if public.pipeline_etapa_protegida(old.slug) then
    raise exception 'Esta etapa é protegida por automações e não pode ser excluída.' using errcode = '42501';
  end if;
  if exists (select 1 from public."BASE_DE_LEADS" where estagio_lead = old.slug) then
    raise exception 'Esta etapa possui leads. Mova-os antes de excluir.' using errcode = '23503';
  end if;
  return old;
end;
$$;

drop trigger if exists trg_impedir_exclusao_etapa_protegida on public.pipeline_etapas;
create trigger trg_impedir_exclusao_etapa_protegida
before delete on public.pipeline_etapas
for each row execute function public.impedir_exclusao_etapa_protegida();

-- A validação passa a usar pipeline_etapas em vez do CHECK estático conhecido.
do $$
declare constraint_row record;
begin
  for constraint_row in
    select c.conname
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'BASE_DE_LEADS'
      and c.contype = 'c'
      and c.conname in (
        'BASE_DE_LEADS_estagio_lead_check',
        'base_de_leads_estagio_lead_check'
      )
  loop
    execute format('alter table public."BASE_DE_LEADS" drop constraint %I', constraint_row.conname);
  end loop;
end;
$$;

create or replace function public.validar_estagio_lead()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.estagio_lead is null or not exists (
    select 1 from public.pipeline_etapas where slug = new.estagio_lead
  ) then
    raise exception 'Etapa do pipeline inexistente: %', coalesce(new.estagio_lead, '(vazia)') using errcode = '23503';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validar_estagio_lead on public."BASE_DE_LEADS";
create trigger trg_validar_estagio_lead
before insert or update of estagio_lead on public."BASE_DE_LEADS"
for each row execute function public.validar_estagio_lead();

create or replace function public.sync_follow_manual_from_estagio()
returns trigger language plpgsql set search_path = public as $$
begin
  new.follow_manual := case
    when lower(coalesce(new.estagio_lead, '')) = 'follow_up' then 'ativo'
    else 'inativo'
  end;

  if new.estagio_lead = 'follow_up'
    and (tg_op = 'INSERT' or old.estagio_lead is distinct from new.estagio_lead)
  then
    new.ja_recebeu_msg := null;
    new.erro_follow_manual := null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_follow_manual_from_estagio on public."BASE_DE_LEADS";
create trigger trg_sync_follow_manual_from_estagio
before insert or update of estagio_lead, follow_manual on public."BASE_DE_LEADS"
for each row execute function public.sync_follow_manual_from_estagio();

update public."BASE_DE_LEADS"
set follow_manual = case when lower(coalesce(estagio_lead, '')) = 'follow_up' then 'ativo' else 'inativo' end
where follow_manual is distinct from case
  when lower(coalesce(estagio_lead, '')) = 'follow_up' then 'ativo'
  else 'inativo'
end;

-- Etiquetas funcionais são resolvidas por nome; IDs variam entre instalações.
insert into public.etiquetas (nome, cor)
select values_to_insert.nome, values_to_insert.cor
from (values
  ('Número Inválido', '#000000'),
  ('follow 1', '#3b82f6'),
  ('follow 2', '#f4c51a')
) as values_to_insert(nome, cor)
where not exists (
  select 1 from public.etiquetas existing
  where lower(btrim(existing.nome)) = lower(btrim(values_to_insert.nome))
);

-- Compatibilidade com o workflow duplicado da Ale's Car. Nesse contrato, os
-- números 27, 28 e 29 são códigos semânticos gravados em BASE_DE_LEADS.etiquetas;
-- eles não são reutilizados como IDs reais no CRM-19-MOTORS.
create or replace function public.compatibilizar_etiquetas_workflow_ales()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  etiqueta_legada bigint;
  etiqueta_nome text;
  etiqueta_real_id bigint;
begin
  if new.etiquetas is null then
    return new;
  end if;

  delete from public.lead_etiquetas le
  using public.etiquetas e
  where le.id_lead = new.id
    and le.id_etiqueta = e.id
    and lower(btrim(e.nome)) in ('número inválido', 'follow 1', 'follow 2');

  foreach etiqueta_legada in array new.etiquetas loop
    etiqueta_nome := case etiqueta_legada
      when 27 then 'Número Inválido'
      when 28 then 'follow 1'
      when 29 then 'follow 2'
      else null
    end;

    if etiqueta_nome is not null then
      select id into etiqueta_real_id
      from public.etiquetas
      where lower(btrim(nome)) = lower(btrim(etiqueta_nome))
      order by id
      limit 1;

      if etiqueta_real_id is not null then
        insert into public.lead_etiquetas (id_lead, id_etiqueta)
        values (new.id, etiqueta_real_id)
        on conflict do nothing;
      end if;
    end if;
  end loop;

  return new;
end;
$$;

revoke all on function public.compatibilizar_etiquetas_workflow_ales() from public;

drop trigger if exists trg_compatibilizar_etiquetas_workflow_ales on public."BASE_DE_LEADS";
create trigger trg_compatibilizar_etiquetas_workflow_ales
after insert or update of etiquetas on public."BASE_DE_LEADS"
for each row execute function public.compatibilizar_etiquetas_workflow_ales();

-- Resposta real do cliente: tipos usuais do Chat Memory do n8n são human e user.
create or replace function public.mover_resposta_para_respondeu_follow_up()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.session_id is not null
    and lower(coalesce(new.message ->> 'type', '')) in ('human', 'user')
  then
    with movidos as (
      update public."BASE_DE_LEADS" l
      set estagio_lead = 'respondeu_follow_up'
      where regexp_replace(coalesce(l.telefone, ''), '[^0-9]', '', 'g') <> ''
        and regexp_replace(l.telefone, '[^0-9]', '', 'g') = regexp_replace(new.session_id::text, '[^0-9]', '', 'g')
        and l.estagio_lead = 'follow_up'
        and lower(coalesce(l.follow_manual, '')) = 'ativo'
        and l.id = (
          select candidate.id
          from public."BASE_DE_LEADS" candidate
          where regexp_replace(coalesce(candidate.telefone, ''), '[^0-9]', '', 'g') =
                regexp_replace(new.session_id::text, '[^0-9]', '', 'g')
            and candidate.estagio_lead = 'follow_up'
          order by candidate.id desc
          limit 1
        )
      returning l.id
    )
    insert into public.lead_historico_estagio (id_lead, estagio_anterior, estagio_novo, usuario)
    select id, 'follow_up', 'respondeu_follow_up', 'Sistema - resposta do cliente'
    from movidos;
  end if;
  return new;
end;
$$;

revoke all on function public.mover_resposta_para_respondeu_follow_up() from public;

drop trigger if exists trg_mover_resposta_para_respondeu_follow_up on public.dezenovemotors_chat_histories;
create trigger trg_mover_resposta_para_respondeu_follow_up
after insert or update of message, session_id on public.dezenovemotors_chat_histories
for each row execute function public.mover_resposta_para_respondeu_follow_up();

-- RPCs atômicas para o workflow; somente a service role pode executá-las.
create or replace function public.registrar_envio_follow_up(
  p_id_lead int4,
  p_estado text,
  p_etiqueta_nome text
) returns void language plpgsql security definer set search_path = public as $$
declare etiqueta_id bigint;
begin
  if p_estado not in ('sim', 'segundo_follow', '2º msg') then
    raise exception 'Estado de follow-up inválido.' using errcode = '22023';
  end if;

  update public."BASE_DE_LEADS"
  set ja_recebeu_msg = p_estado, erro_follow_manual = null
  where id = p_id_lead and estagio_lead = 'follow_up' and follow_manual = 'ativo';

  if not found then return; end if;

  select id into etiqueta_id from public.etiquetas
  where lower(btrim(nome)) = lower(btrim(p_etiqueta_nome)) order by id limit 1;
  if etiqueta_id is not null then
    insert into public.lead_etiquetas (id_lead, id_etiqueta)
    values (p_id_lead, etiqueta_id) on conflict do nothing;
  end if;
end;
$$;

create or replace function public.registrar_erro_follow_up(p_id_lead int4, p_erro text)
returns void language plpgsql security definer set search_path = public as $$
declare
  etiqueta_id bigint;
  v_numero_invalido boolean := lower(coalesce(p_erro, '')) like '%is not on whatsapp%'
    or lower(coalesce(p_erro, '')) like '%not registered%'
    or lower(coalesce(p_erro, '')) like '%invalid number%';
begin
  if v_numero_invalido then
    update public."BASE_DE_LEADS"
    set erro_follow_manual = left(coalesce(p_erro, 'erro'), 500),
        ja_recebeu_msg = 'erro',
        estagio_lead = 'resgate'
    where id = p_id_lead and estagio_lead = 'follow_up';

    if not found then return; end if;

    select id into etiqueta_id from public.etiquetas
    where lower(btrim(nome)) = lower('Número Inválido') order by id limit 1;
    if etiqueta_id is not null then
      insert into public.lead_etiquetas (id_lead, id_etiqueta)
      values (p_id_lead, etiqueta_id) on conflict do nothing;
    end if;

    insert into public.lead_historico_estagio (id_lead, estagio_anterior, estagio_novo, usuario)
    values (p_id_lead, 'follow_up', 'resgate', 'Sistema - número inválido no follow-up');
  else
    update public."BASE_DE_LEADS"
    set erro_follow_manual = left(coalesce(p_erro, 'erro transitório'), 500)
    where id = p_id_lead and estagio_lead = 'follow_up';
  end if;
end;
$$;

create or replace function public.encerrar_follow_up_sem_resposta(p_id_lead int4)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public."BASE_DE_LEADS"
  set estagio_lead = 'resgate'
  where id = p_id_lead
    and estagio_lead = 'follow_up'
    and follow_manual = 'ativo'
    and ja_recebeu_msg in ('segundo_follow', '2º msg');

  if found then
    insert into public.lead_historico_estagio (id_lead, estagio_anterior, estagio_novo, usuario)
    values (p_id_lead, 'follow_up', 'resgate', 'Sistema - cadência encerrada sem resposta');
  end if;
end;
$$;

revoke all on function public.registrar_envio_follow_up(int4, text, text) from public, anon, authenticated;
revoke all on function public.registrar_erro_follow_up(int4, text) from public, anon, authenticated;
revoke all on function public.encerrar_follow_up_sem_resposta(int4) from public, anon, authenticated;
grant execute on function public.registrar_envio_follow_up(int4, text, text) to service_role;
grant execute on function public.registrar_erro_follow_up(int4, text) to service_role;
grant execute on function public.encerrar_follow_up_sem_resposta(int4) to service_role;

grant select on public.pipeline_etapas to authenticated;
grant insert, update, delete on public.pipeline_etapas to authenticated;
grant usage, select on sequence public.pipeline_etapas_id_seq to authenticated;
alter table public.pipeline_etapas enable row level security;

drop policy if exists pipeline_etapas_select on public.pipeline_etapas;
create policy pipeline_etapas_select on public.pipeline_etapas
for select to authenticated using (true);

drop policy if exists pipeline_etapas_write on public.pipeline_etapas;
create policy pipeline_etapas_write on public.pipeline_etapas
for all to authenticated
using (public.get_my_cargo() in ('admin_master', 'admin', 'gerente'))
with check (public.get_my_cargo() in ('admin_master', 'admin', 'gerente'));
